import '@/styles/globals.css'

const metadata = {
  title: "Book Connect",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />
}

